import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { jsPDF } from 'jspdf';

const ViewSingleBill = () => {
    const { id } = useParams();
    const [bill, setBill] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    // Fetch the bill data
    useEffect(() => {
        const fetchBill = async () => {
            try {
                const response = await fetch(`http://localhost:8084/bills/${id}`);
                if (!response.ok) {
                    throw new Error('Bill not found');
                }
                const data = await response.json();
                setBill(data);
            } catch (err) {
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        fetchBill();
    }, [id]);

    const downloadPDF = () => {
        const doc = new jsPDF();

        // Modern-looking PDF layout
        doc.setFont("helvetica");
        doc.setFontSize(16);
        doc.text(`Bill ID: ${bill.id}`, 20, 20);
        doc.setFontSize(12);
        doc.text(`Name: ${bill.name}`, 20, 30);
        doc.text(`Film Name: ${bill.filmName}`, 20, 40);
        doc.text(`Seat No: ${bill.seatNo}`, 20, 50);
        doc.text(`Phone: ${bill.phone}`, 20, 60);
        doc.text(`Total: Rs:${bill.total.toFixed(2)}`, 20, 70);
        doc.text(`Date: ${(bill.date).toLocaleString()}`, 20, 80);

        // Draw a line to separate sections
        doc.setLineWidth(0.5);
        doc.line(20, 90, 190, 90);

        // Add footer
        doc.setFontSize(10);
        doc.text("Generated by MovieMate Booking System", 20, 285);

        // Save the PDF
        doc.save(`bill_${bill.id}.pdf`);
    };

    if (loading) {
        return <div className="text-center text-gray-500">Loading bill...</div>;
    }

    if (error) {
        return <div className="text-center text-red-500">Error: {error}</div>;
    }

    return (
        <div className="min-h-screen bg-red-50 py-10 px-4">
            <div className="bg-white p-8 rounded-lg shadow-lg max-w-3xl mx-auto">
                <h1 className="text-2xl font-bold text-center mb-6">Bill Details</h1>
                <div className="space-y-4">
                    <p><strong>Bill ID:</strong> {bill.id}</p>
                    <p><strong>Date:</strong> {(bill.date).toLocaleString()}</p>
                    <p><strong>Name:</strong> {bill.name}</p>
                    <p><strong>Film Name:</strong> {bill.filmName}</p>
                    <p><strong>Seat Number:</strong> {bill.seatNo}</p>
                    <p><strong>Phone:</strong> {bill.phone}</p>
                    <p><strong>Total:</strong> Rs: {bill.total.toFixed(2)}</p>

                </div>
                <div className="text-center mt-6">
                    <button
                        onClick={downloadPDF}
                        className="px-6 py-2 bg-red-600 text-white font-semibold rounded-full hover:bg-red-700"
                    >
                        Download PDF
                    </button>
                </div>
            </div>
        </div>
    )
}

export default ViewSingleBill





